name: veinmind-weakpass
on: [push]
jobs:
  build-amd64:
    runs-on: ubuntu-latest
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.1'
      - run: /bin/bash scripts/libveinmind/install_libveinmind_${CI_GOARCH}.sh
      - run: cd veinmind-weakpass && /bin/bash -x ../scripts/build/build_veinmind_weakpass_${CI_GOARCH}.sh
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-weakpass-amd64
          path: ./veinmind-weakpass/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-weakpass_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./veinmind-weakpass/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-weakpass_${{env.CI_GOOS}}_${{env.CI_GOARCH}}